apiVersion: v1
kind: Service
metadata:
  name: scheduled-sync-service
spec:
  selector:
    app: scheduled-sync-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP