spring:
  kafka:
    consumer:
      group-id: scheduled-sync-group
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
    listener:
      concurrency: 3
